<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marta Vaquerizo, María del Mar Martínez y Paula Ibáñez">

<title>Detención de fraude en las reclamaciones de seguros de vehículos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="FraudeCocheQuarto16_files/libs/clipboard/clipboard.min.js"></script>
<script src="FraudeCocheQuarto16_files/libs/quarto-html/quarto.js"></script>
<script src="FraudeCocheQuarto16_files/libs/quarto-html/popper.min.js"></script>
<script src="FraudeCocheQuarto16_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FraudeCocheQuarto16_files/libs/quarto-html/anchor.min.js"></script>
<link href="FraudeCocheQuarto16_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FraudeCocheQuarto16_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FraudeCocheQuarto16_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FraudeCocheQuarto16_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FraudeCocheQuarto16_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detención de fraude en las reclamaciones de seguros de vehículos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marta Vaquerizo, María del Mar Martínez y Paula Ibáñez </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="resumen-del-proyecto" class="level3">
<h3 class="anchored" data-anchor-id="resumen-del-proyecto">Resumen del proyecto</h3>
<p>Se trata de una base de datos real proporcionada por Oracle, utilizada en contextos educativos para enseñar sobre la detección de fraudes en seguros de automóviles en Estados Unidos. El fraude en los seguros de automóviles implica llevar a cabo reclamos falsos o exagerados relacionados con daños materiales o lesiones personales tras un accidente.</p>
<p>Fuente: Kaggle</p>
</section>
<section id="objetivo" class="level3">
<h3 class="anchored" data-anchor-id="objetivo">Objetivo</h3>
<p>Nuestro objetivo es desarrollar un sistema que permita identificar si los casos son fraudulentos o no, reduciendo así la necesidad de que un equipo de especialistas analice manualmente cada caso.</p>
</section>
<section id="introducción" class="level3">
<h3 class="anchored" data-anchor-id="introducción">Introducción</h3>
<p>Este documento evalua el rendimiento de los métodos de regresión penalizada (Ridge, Lasso y Elastic-Net) en un problema de clasificación binaria. Los pasos que se seguiran son los siguientes:</p>
<ol type="1">
<li>Análisis exploratorio de datos (EDA).</li>
<li>Preprocesamiento automático mediante recetas.</li>
<li>Creación de los modelos y workflows.</li>
<li>Tuneado de hiperparámetros con validación cruzada.</li>
<li>Assessment con Validación Cruzada.</li>
<li>Predicción en el conjunto de prueba y evaluación final.</li>
</ol>
<p>En primer lugar, se cargan las librerias necesarias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(recipes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'recipes'

The following object is masked from 'package:stringr':

    fixed

The following object is masked from 'package:stats':

    step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: Matrix

Adjuntando el paquete: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.2.0 ──
✔ broom        1.0.7     ✔ tune         1.2.1
✔ dials        1.3.0     ✔ workflows    1.1.4
✔ infer        1.0.7     ✔ workflowsets 1.1.0
✔ modeldata    1.4.0     ✔ yardstick    1.3.1
✔ parsnip      1.2.1     
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ Matrix::expand()  masks tidyr::expand()
✖ plotly::filter()  masks dplyr::filter(), stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ Matrix::pack()    masks tidyr::pack()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
✖ Matrix::unpack()  masks tidyr::unpack()
✖ Matrix::update()  masks recipes::update(), stats::update()
• Search for functions across packages at https://www.tidymodels.org/find/</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Matrix)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tune)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE) <span class="co"># alternativa para el SMOTE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded ROSE 0.0-4</code></pre>
</div>
</div>
<p>A continuación, importamos el dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="st">"C:/Users/34672/Documents/Big Data and Bussines Analytics/Minería de datos/Assigment 1/fraud_oracle.csv"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(file_path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análisis-exploratorio-de-datos-eda" class="level1">
<h1><em>1) Análisis Exploratorio de Datos (EDA)</em></h1>
<p>En primer lugar, se examina sus dimensiones, estructura y estadísticas descriptivas básicas para obtener una visión general de su contenido y características:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Estudio del dataset"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estudio del dataset"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data) <span class="co"># Dimensiones </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15420    33</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data) <span class="co"># Primeras filas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Month WeekOfMonth DayOfWeek   Make AccidentArea DayOfWeekClaimed MonthClaimed
1   Dec           5 Wednesday  Honda        Urban          Tuesday          Jan
2   Jan           3 Wednesday  Honda        Urban           Monday          Jan
3   Oct           5    Friday  Honda        Urban         Thursday          Nov
4   Jun           2  Saturday Toyota        Rural           Friday          Jul
5   Jan           5    Monday  Honda        Urban          Tuesday          Feb
6   Oct           4    Friday  Honda        Urban        Wednesday          Nov
  WeekOfMonthClaimed    Sex MaritalStatus Age         Fault        PolicyType
1                  1 Female        Single  21 Policy Holder Sport - Liability
2                  4   Male        Single  34 Policy Holder Sport - Collision
3                  2   Male       Married  47 Policy Holder Sport - Collision
4                  1   Male       Married  65   Third Party Sedan - Liability
5                  2 Female        Single  27   Third Party Sport - Collision
6                  1   Male        Single  20   Third Party Sport - Collision
  VehicleCategory    VehiclePrice FraudFound_P PolicyNumber RepNumber
1           Sport more than 69000            0            1        12
2           Sport more than 69000            0            2        15
3           Sport more than 69000            0            3         7
4           Sport  20000 to 29000            0            4         4
5           Sport more than 69000            0            5         3
6           Sport more than 69000            0            6        12
  Deductible DriverRating Days_Policy_Accident Days_Policy_Claim
1        300            1         more than 30      more than 30
2        400            4         more than 30      more than 30
3        400            3         more than 30      more than 30
4        400            2         more than 30      more than 30
5        400            1         more than 30      more than 30
6        400            3         more than 30      more than 30
  PastNumberOfClaims AgeOfVehicle AgeOfPolicyHolder PoliceReportFiled
1               none      3 years          26 to 30                No
2               none      6 years          31 to 35               Yes
3                  1      7 years          41 to 50                No
4                  1  more than 7          51 to 65               Yes
5               none      5 years          31 to 35                No
6               none      5 years          21 to 25                No
  WitnessPresent AgentType NumberOfSuppliments AddressChange_Claim NumberOfCars
1             No  External                none              1 year       3 to 4
2             No  External                none           no change    1 vehicle
3             No  External                none           no change    1 vehicle
4             No  External         more than 5           no change    1 vehicle
5             No  External                none           no change    1 vehicle
6             No  External              3 to 5           no change    1 vehicle
  Year BasePolicy
1 1994  Liability
2 1994  Collision
3 1994  Collision
4 1994  Liability
5 1994  Collision
6 1994  Collision</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data) <span class="co"># Estructura general</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15,420
Columns: 33
$ Month                &lt;chr&gt; "Dec", "Jan", "Oct", "Jun", "Jan", "Oct", "Feb", …
$ WeekOfMonth          &lt;int&gt; 5, 3, 5, 2, 5, 4, 1, 1, 4, 3, 2, 5, 3, 5, 5, 4, 4…
$ DayOfWeek            &lt;chr&gt; "Wednesday", "Wednesday", "Friday", "Saturday", "…
$ Make                 &lt;chr&gt; "Honda", "Honda", "Honda", "Toyota", "Honda", "Ho…
$ AccidentArea         &lt;chr&gt; "Urban", "Urban", "Urban", "Rural", "Urban", "Urb…
$ DayOfWeekClaimed     &lt;chr&gt; "Tuesday", "Monday", "Thursday", "Friday", "Tuesd…
$ MonthClaimed         &lt;chr&gt; "Jan", "Jan", "Nov", "Jul", "Feb", "Nov", "Feb", …
$ WeekOfMonthClaimed   &lt;int&gt; 1, 4, 2, 1, 2, 1, 3, 4, 5, 3, 3, 5, 3, 1, 1, 5, 1…
$ Sex                  &lt;chr&gt; "Female", "Male", "Male", "Male", "Female", "Male…
$ MaritalStatus        &lt;chr&gt; "Single", "Single", "Married", "Married", "Single…
$ Age                  &lt;int&gt; 21, 34, 47, 65, 27, 20, 36, 0, 30, 42, 71, 52, 28…
$ Fault                &lt;chr&gt; "Policy Holder", "Policy Holder", "Policy Holder"…
$ PolicyType           &lt;chr&gt; "Sport - Liability", "Sport - Collision", "Sport …
$ VehicleCategory      &lt;chr&gt; "Sport", "Sport", "Sport", "Sport", "Sport", "Spo…
$ VehiclePrice         &lt;chr&gt; "more than 69000", "more than 69000", "more than …
$ FraudFound_P         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ PolicyNumber         &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15…
$ RepNumber            &lt;int&gt; 12, 15, 7, 4, 3, 12, 14, 1, 7, 7, 7, 13, 11, 12, …
$ Deductible           &lt;int&gt; 300, 400, 400, 400, 400, 400, 400, 400, 400, 400,…
$ DriverRating         &lt;int&gt; 1, 4, 3, 2, 1, 3, 1, 4, 4, 1, 3, 1, 1, 3, 1, 1, 4…
$ Days_Policy_Accident &lt;chr&gt; "more than 30", "more than 30", "more than 30", "…
$ Days_Policy_Claim    &lt;chr&gt; "more than 30", "more than 30", "more than 30", "…
$ PastNumberOfClaims   &lt;chr&gt; "none", "none", "1", "1", "none", "none", "1", "1…
$ AgeOfVehicle         &lt;chr&gt; "3 years", "6 years", "7 years", "more than 7", "…
$ AgeOfPolicyHolder    &lt;chr&gt; "26 to 30", "31 to 35", "41 to 50", "51 to 65", "…
$ PoliceReportFiled    &lt;chr&gt; "No", "Yes", "No", "Yes", "No", "No", "No", "No",…
$ WitnessPresent       &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No", "…
$ AgentType            &lt;chr&gt; "External", "External", "External", "External", "…
$ NumberOfSuppliments  &lt;chr&gt; "none", "none", "none", "more than 5", "none", "3…
$ AddressChange_Claim  &lt;chr&gt; "1 year", "no change", "no change", "no change", …
$ NumberOfCars         &lt;chr&gt; "3 to 4", "1 vehicle", "1 vehicle", "1 vehicle", …
$ Year                 &lt;int&gt; 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1…
$ BasePolicy           &lt;chr&gt; "Liability", "Collision", "Collision", "Liability…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data) <span class="co"># Estadísticas básicas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Month            WeekOfMonth     DayOfWeek             Make          
 Length:15420       Min.   :1.000   Length:15420       Length:15420      
 Class :character   1st Qu.:2.000   Class :character   Class :character  
 Mode  :character   Median :3.000   Mode  :character   Mode  :character  
                    Mean   :2.789                                        
                    3rd Qu.:4.000                                        
                    Max.   :5.000                                        
 AccidentArea       DayOfWeekClaimed   MonthClaimed       WeekOfMonthClaimed
 Length:15420       Length:15420       Length:15420       Min.   :1.000     
 Class :character   Class :character   Class :character   1st Qu.:2.000     
 Mode  :character   Mode  :character   Mode  :character   Median :3.000     
                                                          Mean   :2.694     
                                                          3rd Qu.:4.000     
                                                          Max.   :5.000     
     Sex            MaritalStatus           Age           Fault          
 Length:15420       Length:15420       Min.   : 0.00   Length:15420      
 Class :character   Class :character   1st Qu.:31.00   Class :character  
 Mode  :character   Mode  :character   Median :38.00   Mode  :character  
                                       Mean   :39.86                     
                                       3rd Qu.:48.00                     
                                       Max.   :80.00                     
  PolicyType        VehicleCategory    VehiclePrice        FraudFound_P    
 Length:15420       Length:15420       Length:15420       Min.   :0.00000  
 Class :character   Class :character   Class :character   1st Qu.:0.00000  
 Mode  :character   Mode  :character   Mode  :character   Median :0.00000  
                                                          Mean   :0.05986  
                                                          3rd Qu.:0.00000  
                                                          Max.   :1.00000  
  PolicyNumber     RepNumber        Deductible     DriverRating  
 Min.   :    1   Min.   : 1.000   Min.   :300.0   Min.   :1.000  
 1st Qu.: 3856   1st Qu.: 5.000   1st Qu.:400.0   1st Qu.:1.000  
 Median : 7710   Median : 8.000   Median :400.0   Median :2.000  
 Mean   : 7710   Mean   : 8.483   Mean   :407.7   Mean   :2.488  
 3rd Qu.:11565   3rd Qu.:12.000   3rd Qu.:400.0   3rd Qu.:3.000  
 Max.   :15420   Max.   :16.000   Max.   :700.0   Max.   :4.000  
 Days_Policy_Accident Days_Policy_Claim  PastNumberOfClaims AgeOfVehicle      
 Length:15420         Length:15420       Length:15420       Length:15420      
 Class :character     Class :character   Class :character   Class :character  
 Mode  :character     Mode  :character   Mode  :character   Mode  :character  
                                                                              
                                                                              
                                                                              
 AgeOfPolicyHolder  PoliceReportFiled  WitnessPresent      AgentType        
 Length:15420       Length:15420       Length:15420       Length:15420      
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
 NumberOfSuppliments AddressChange_Claim NumberOfCars            Year     
 Length:15420        Length:15420        Length:15420       Min.   :1994  
 Class :character    Class :character    Class :character   1st Qu.:1994  
 Mode  :character    Mode  :character    Mode  :character   Median :1995  
                                                            Mean   :1995  
                                                            3rd Qu.:1996  
                                                            Max.   :1996  
  BasePolicy       
 Length:15420      
 Class :character  
 Mode  :character  
                   
                   
                   </code></pre>
</div>
</div>
<section id="variables-categóricas-y-numéricas" class="level4">
<h4 class="anchored" data-anchor-id="variables-categóricas-y-numéricas">Variables Categóricas y Numéricas</h4>
<p>En esta sección se clasifican las variables del dataset en categóricas y numéricas, lo cual es fundamental para aplicar el análisis y transformaciones específicas según su tipo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Tipos de variables:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tipos de variables:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[<span class="fu">sapply</span>(data, is.character)]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>numerical_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[<span class="fu">sapply</span>(data, is.numeric)]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(numerical_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "WeekOfMonth"        "WeekOfMonthClaimed" "Age"               
[4] "FraudFound_P"       "PolicyNumber"       "RepNumber"         
[7] "Deductible"         "DriverRating"       "Year"              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(categorical_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Month"                "DayOfWeek"            "Make"                
 [4] "AccidentArea"         "DayOfWeekClaimed"     "MonthClaimed"        
 [7] "Sex"                  "MaritalStatus"        "Fault"               
[10] "PolicyType"           "VehicleCategory"      "VehiclePrice"        
[13] "Days_Policy_Accident" "Days_Policy_Claim"    "PastNumberOfClaims"  
[16] "AgeOfVehicle"         "AgeOfPolicyHolder"    "PoliceReportFiled"   
[19] "WitnessPresent"       "AgentType"            "NumberOfSuppliments" 
[22] "AddressChange_Claim"  "NumberOfCars"         "BasePolicy"          </code></pre>
</div>
</div>
<p>Posteriormente, se visualizan las distribuciones de las variables numéricas mediante histogramas, lo que ayuda a identificar patrones, posibles valores atípicos y rangos de valores, proporcionando información clave para el análisis y modelado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribuciones de las variables numéricas</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(numerical_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(variable, value) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> variable)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de Variables Numéricas"</span>, <span class="at">x =</span> <span class="st">"Valor"</span>, <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="detección-de-valores-faltantes" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-valores-faltantes">Detección de Valores Faltantes</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>missing_values[missing_values <span class="sc">&gt;</span> <span class="dv">0</span>]  <span class="co"># Mostrar solo columnas con NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>named numeric(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>No hay columnas con valores faltantes en el conjunto de datos analizado. Esto implica que no es necesario realizar un tratamiento adicional, como imputación o eliminación de valores, relacionado con datos faltantes.</p>
</section>
<section id="detección-de-valores-iguales-a-0" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-valores-iguales-a-0">Detección de Valores Iguales a 0</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Detección de valores iguales a 0:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Detección de valores iguales a 0:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>zero_values <span class="ot">&lt;-</span> <span class="fu">colSums</span>(data <span class="sc">==</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>zero_values[zero_values <span class="sc">&gt;</span> <span class="dv">0</span>]  <span class="co"># Mostrar solo columnas con valores iguales a 0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DayOfWeekClaimed     MonthClaimed              Age     FraudFound_P 
               1                1              320            14497 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(zero_values) <span class="co">#Hay 0 en la columna AGE 320 </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se detectan ceros en la columna <code>Age</code>, por lo cual al ser un valor mínimo decidimos eliminarlos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[data<span class="sc">$</span>Age <span class="sc">!=</span> <span class="dv">0</span>, ]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(data<span class="sc">$</span>Age <span class="sc">==</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Nos damos cuenta que al eliminar los valores de 0 en Age, se eliminan los valores de 0 en esta otra columna, lo cual correspondía justo con las pólizas que tienen personas con una edad de 16-17 años.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>zeros_AgeOfPolicyHolder <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>Age <span class="sc">==</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Número de ceros en la columna 'AgeOfPolicyHolder':"</span>, zeros_AgeOfPolicyHolder, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Número de ceros en la columna 'AgeOfPolicyHolder': 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Se quita una categoria entera, la cual tenia sentido porque no hay polizas para niños de 16 a 17 años´</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>age_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>AgeOfPolicyHolder)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(age_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
18 to 20 21 to 25 26 to 30 31 to 35 36 to 40 41 to 50 51 to 65  over 65 
      15      108      613     5593     4043     2828     1392      508 </code></pre>
</div>
</div>
</section>
<section id="eliminación-de-columnas-innecesarias" class="level4">
<h4 class="anchored" data-anchor-id="eliminación-de-columnas-innecesarias">Eliminación de Columnas Innecesarias</h4>
<p>Estas columnas se eliminan porque:</p>
<ol type="1">
<li><p><strong>Irrelevancia</strong>: No aportan información útil para la predicción o el análisis.</p></li>
<li><p><strong>Redundancia</strong>: Su información ya está representada en otras variables.</p></li>
<li><p><strong>Colinealidad</strong>: Pueden estar altamente correlacionadas con otras columnas.</p></li>
<li><p><strong>Ruido</strong>: Como identificadores (<code>PolicyNumber</code>), no añaden valor predictivo.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Month"                "WeekOfMonth"          "DayOfWeek"           
 [4] "Make"                 "AccidentArea"         "DayOfWeekClaimed"    
 [7] "MonthClaimed"         "WeekOfMonthClaimed"   "Sex"                 
[10] "MaritalStatus"        "Age"                  "Fault"               
[13] "PolicyType"           "VehicleCategory"      "VehiclePrice"        
[16] "FraudFound_P"         "PolicyNumber"         "RepNumber"           
[19] "Deductible"           "DriverRating"         "Days_Policy_Accident"
[22] "Days_Policy_Claim"    "PastNumberOfClaims"   "AgeOfVehicle"        
[25] "AgeOfPolicyHolder"    "PoliceReportFiled"    "WitnessPresent"      
[28] "AgentType"            "NumberOfSuppliments"  "AddressChange_Claim" 
[31] "NumberOfCars"         "Year"                 "BasePolicy"          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>data_cleaned <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Month, <span class="sc">-</span>WeekOfMonth, <span class="sc">-</span>DayOfWeek, <span class="sc">-</span>DayOfWeekClaimed, <span class="sc">-</span>MonthClaimed, <span class="sc">-</span>WeekOfMonthClaimed, <span class="sc">-</span>PolicyNumber, <span class="sc">-</span>Age)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(data_cleaned))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Make"                 "AccidentArea"         "Sex"                 
 [4] "MaritalStatus"        "Fault"                "PolicyType"          
 [7] "VehicleCategory"      "VehiclePrice"         "FraudFound_P"        
[10] "RepNumber"            "Deductible"           "DriverRating"        
[13] "Days_Policy_Accident" "Days_Policy_Claim"    "PastNumberOfClaims"  
[16] "AgeOfVehicle"         "AgeOfPolicyHolder"    "PoliceReportFiled"   
[19] "WitnessPresent"       "AgentType"            "NumberOfSuppliments" 
[22] "AddressChange_Claim"  "NumberOfCars"         "Year"                
[25] "BasePolicy"          </code></pre>
</div>
</div>
</section>
<section id="análisis-de-la-variable-objetivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-la-variable-objetivo">Análisis de la Variable Objetivo</h2>
<p>Verificamos la distrivución de la variable target y creamos un gráfico para visualizarla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar la distribución de la variable target</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>fraud_distribution <span class="ot">&lt;-</span> <span class="fu">table</span>(data_cleaned<span class="sc">$</span>FraudFound_P)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fraud_distribution) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
14208   892 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización gráfica con ggplot2</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(FraudFound_P), <span class="at">fill =</span> <span class="fu">as.factor</span>(FraudFound_P))) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>)) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución de la variable objetivo 'FraudFound_P'"</span>,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fraude Encontrado (0: No, 1: Sí)"</span>,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Fraude Encontrado"</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El desbalanceo en la variable <code>Fraud</code> ocurre porque en el mundo real los casos de fraude (clase 1) son mucho menos frecuentes que los casos no fraudulentos (clase 0). Esto refleja la naturaleza del problema: la mayoría de las transacciones o eventos son legítimos, y solo un pequeño porcentaje son fraudulentos.</p>
</section>
<section id="aplicación-de-smote" class="level2">
<h2 class="anchored" data-anchor-id="aplicación-de-smote">Aplicación de SMOTE</h2>
<p>Primero verificamos el tipo de datos que tenemos y nos aseguramos que los datos sean factores, para poder aplicar SMOTE con la libreria ROSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Verificar tipos de datos antes de aplicar ROSE:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Verificar tipos de datos antes de aplicar ROSE:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_cleaned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15,100
Columns: 25
$ Make                 &lt;chr&gt; "Honda", "Honda", "Honda", "Toyota", "Honda", "Ho…
$ AccidentArea         &lt;chr&gt; "Urban", "Urban", "Urban", "Rural", "Urban", "Urb…
$ Sex                  &lt;chr&gt; "Female", "Male", "Male", "Male", "Female", "Male…
$ MaritalStatus        &lt;chr&gt; "Single", "Single", "Married", "Married", "Single…
$ Fault                &lt;chr&gt; "Policy Holder", "Policy Holder", "Policy Holder"…
$ PolicyType           &lt;chr&gt; "Sport - Liability", "Sport - Collision", "Sport …
$ VehicleCategory      &lt;chr&gt; "Sport", "Sport", "Sport", "Sport", "Sport", "Spo…
$ VehiclePrice         &lt;chr&gt; "more than 69000", "more than 69000", "more than …
$ FraudFound_P         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ RepNumber            &lt;int&gt; 12, 15, 7, 4, 3, 12, 14, 7, 7, 7, 13, 11, 3, 16, …
$ Deductible           &lt;int&gt; 300, 400, 400, 400, 400, 400, 400, 400, 400, 400,…
$ DriverRating         &lt;int&gt; 1, 4, 3, 2, 1, 3, 1, 4, 1, 3, 1, 1, 1, 1, 4, 1, 1…
$ Days_Policy_Accident &lt;chr&gt; "more than 30", "more than 30", "more than 30", "…
$ Days_Policy_Claim    &lt;chr&gt; "more than 30", "more than 30", "more than 30", "…
$ PastNumberOfClaims   &lt;chr&gt; "none", "none", "1", "1", "none", "none", "1", "n…
$ AgeOfVehicle         &lt;chr&gt; "3 years", "6 years", "7 years", "more than 7", "…
$ AgeOfPolicyHolder    &lt;chr&gt; "26 to 30", "31 to 35", "41 to 50", "51 to 65", "…
$ PoliceReportFiled    &lt;chr&gt; "No", "Yes", "No", "Yes", "No", "No", "No", "No",…
$ WitnessPresent       &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "Yes", …
$ AgentType            &lt;chr&gt; "External", "External", "External", "External", "…
$ NumberOfSuppliments  &lt;chr&gt; "none", "none", "none", "more than 5", "none", "3…
$ AddressChange_Claim  &lt;chr&gt; "1 year", "no change", "no change", "no change", …
$ NumberOfCars         &lt;chr&gt; "3 to 4", "1 vehicle", "1 vehicle", "1 vehicle", …
$ Year                 &lt;int&gt; 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1…
$ BasePolicy           &lt;chr&gt; "Liability", "Collision", "Collision", "Liability…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurar que las columnas categóricas sean factores</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(data_cleaned)[<span class="fu">sapply</span>(data_cleaned, is.character)]</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>data_cleaned[categorical_cols] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(data_cleaned[categorical_cols], as.factor)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurar que la variable objetivo sea un factor</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>data_cleaned<span class="sc">$</span>FraudFound_P <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_cleaned<span class="sc">$</span>FraudFound_P)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># Para reproducibilidad</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>data_smote <span class="ot">&lt;-</span> <span class="fu">ROSE</span>(FraudFound_P <span class="sc">~</span> ., <span class="at">data =</span> data_cleaned, <span class="at">seed =</span> <span class="dv">42</span>)<span class="sc">$</span>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es una técnica utilizada para abordar el desbalance de clases. En lugar de simplemente duplicar muestras de la clase minoritaria, SMOTE crea nuevas observaciones sintéticas generando datos intermedios entre los puntos existentes de la clase minoritaria. Esto ayuda a: evitar el sobreajuste y equilibrar el dataset.</p>
<p>Volvemos a ver la distribución de la variable target después de su aplicación, creamos otro gráfico de barras para ver el cambio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar la distribución de la variable objetivo después de ROSE</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Distribución después de aplicar ROSE:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Distribución después de aplicar ROSE:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>fraud_distribution_smote <span class="ot">&lt;-</span> <span class="fu">table</span>(data_smote<span class="sc">$</span>FraudFound_P)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fraud_distribution_smote)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
7521 7579 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_smote, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(FraudFound_P), <span class="at">fill =</span> <span class="fu">as.factor</span>(FraudFound_P))) <span class="sc">+</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>)) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución de la variable objetivo 'FraudFound_P' después de ROSE"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fraude Encontrado (0: No, 1: Sí)"</span>,</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Fraude Encontrado"</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al aplicar SMOTE, la distribución de las clases cambia y ambas (fraude y no fraude) tienen un número similar de observaciones (7521 para clase 0 y 7579 para clase 1). Esto sucede porque SMOTE <strong>crea nuevas muestras sintéticas de la clase minoritaria</strong> (fraude) hasta que se iguala o se acerca en número a la clase mayoritaria (no fraude).</p>
<p>La distribución 50-50 creada al aplicar SMOTE puede generar un <strong>problema de representatividad</strong> si la distribución original del mundo real estaba altamente desbalanceada</p>
</section>
<section id="análisis-de-los-features" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-los-features">Análisis de los Features</h2>
<section id="distribución-por-sexo" class="level4">
<h4 class="anchored" data-anchor-id="distribución-por-sexo"><em>01. Distribución por Sexo</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>df_fraud <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FraudFound_P <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>fraud_counts_sex <span class="ot">&lt;-</span> df_fraud <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Sex, <span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Percentage =</span> (Count <span class="sc">/</span> <span class="fu">sum</span>(Count)) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fraud_counts_sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Sex Count Percentage
1 Female   105    11.7713
2   Male   787    88.2287</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">fill =</span> Sex)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de la variable 'Sex'"</span>,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sexo"</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Sexo"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/sex-variable-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En la gráfica de la distribución de la variable Sex, nos encontramos nuevamente con un desbalance, pero en este caso del género. La cantidad de registros asociados a hombres (“Male”) es significativamente mayor que la de mujeres (“Female”).</p>
</section>
<section id="fraude-por-edad" class="level4">
<h4 class="anchored" data-anchor-id="fraude-por-edad"><em>02. Fraude por Edad</em></h4>
<p>A pesar de su eliminación porque solo añade ruido y ya existe una columna relacionada con la edad (AgePolicyHolder) hemos querido analizar un poco los datos. MEJORAR</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separar datos de fraude y no fraude</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>df_fraud <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FraudFound_P <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>df_non_fraud <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FraudFound_P <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo por edad</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>df_counts_age <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Age, <span class="at">name =</span> <span class="st">"Total"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Age)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>df_counts_fraud <span class="ot">&lt;-</span> df_fraud <span class="sc">%&gt;%</span> </span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Age, <span class="at">name =</span> <span class="st">"Fraud"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Age)</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular porcentajes de fraude por edad</span></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a>df_percentages_fraud <span class="ot">&lt;-</span> df_counts_age <span class="sc">%&gt;%</span> </span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_counts_fraud, <span class="at">by =</span> <span class="st">"Age"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fraud =</span> <span class="fu">replace_na</span>(Fraud, <span class="dv">0</span>),</span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">Percentage =</span> <span class="fu">round</span>((Fraud <span class="sc">/</span> Total) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df_percentages_fraud)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Age Total Fraud Percentage
1   16     9     1      11.11
2   17     6     1      16.67
3   18    48     8      16.67
4   19    32     5      15.62
5   20    28     3      10.71
6   21   127     4       3.15
7   22   125    12       9.60
8   23   122     3       2.46
9   24   135     8       5.93
10  25   104     6       5.77
11  26   535    32       5.98
12  27   540    32       5.93
13  28   560    38       6.79
14  29   552    31       5.62
15  30   596    37       6.21
16  31   550    35       6.36
17  32   544    46       8.46
18  33   574    29       5.05
19  34   573    29       5.06
20  35   569    51       8.96
21  36   406    24       5.91
22  37   410    22       5.37
23  38   384    22       5.73
24  39   435    28       6.44
25  40   383    31       8.09
26  41   423    31       7.33
27  42   401    14       3.49
28  43   404    24       5.94
29  44   411    20       4.87
30  45   386    21       5.44
31  46   296    27       9.12
32  47   308     8       2.60
33  48   291    15       5.15
34  49   265     9       3.40
35  50   290    17       5.86
36  51   279    18       6.45
37  52   276     9       3.26
38  53   253    16       6.32
39  54   288    12       4.17
40  55   282    13       4.61
41  56   146     4       2.74
42  57   144     8       5.56
43  58   134     8       5.97
44  59   138     5       3.62
45  60   156     9       5.77
46  61   145     9       6.21
47  62   112     5       4.46
48  63   136     5       3.68
49  64   146    10       6.85
50  65   135     7       5.19
51  66    42     5      11.90
52  67    31     4      12.90
53  68    32     4      12.50
54  69    32     1       3.12
55  70    27     0       0.00
56  71    40     0       0.00
57  72    45     6      13.33
58  73    32     1       3.12
59  74    35     1       2.86
60  75    34     0       0.00
61  76    42     3       7.14
62  77    29     1       3.45
63  78    35     2       5.71
64  79    20     1       5.00
65  80    32     1       3.12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de barras con ggplot2</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_percentages_fraud, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Percentage)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">6</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dotdash"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Línea de referencia</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Detección de Fraude por Edad"</span>,</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Edad"</span>,</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Porcentaje"</span></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">2</span>)) <span class="sc">+</span> <span class="co"># Configuración de rango y ticks</span></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">18</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/fraud-by-age-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observamos que los porcentajes de fraude son más altos en edades jóvenes, especialmente en el rango de 18 a 25 años, donde el porcentaje supera consistentemente el 10% y en algunos casos alcanza hasta el 16%.</p>
<p>Por otro lado, a medida que la edad avanza hacia los 30-50 años, los porcentajes de fraude tienden a estabilizarse alrededor del promedio (línea roja, ~6%).</p>
<p>Por ultimo, en edades mayores (alrededor de los 60-80 años), se observa un leve aumento en algunos casos, pero no tan marcado como en los jóvenes.</p>
<p><strong>Conclusion:</strong></p>
<p>Hay mayor riesgo en edades jóvenes: Los datos sugieren que los titulares más jóvenes (18-25 años) tienen una mayor probabilidad de estar involucrados en casos de fraude en comparación con otros grupos etarios.</p>
<p>Las aseguradoras podrían prestar especial atención a los grupos más jóvenes al diseñar estrategias de mitigación de fraude, como sistemas de evaluación de riesgos más estrictos o monitoreo adicional para estos clientes.</p>
</section>
<section id="distribución-de-driverrating" class="level4">
<h4 class="anchored" data-anchor-id="distribución-de-driverrating"><em>04. Distribución de DriverRating</em></h4>
<p>Esta variable nos llamo la atención porque esta relacionada con el rating o valoración que tienen los conductores y queriamos ver su distribución</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Distribución de la variable 'DriverRating':</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Distribución de la variable 'DriverRating':</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(data<span class="sc">$</span>DriverRating))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4 
3866 3721 3788 3725 </code></pre>
</div>
</div>
<p>La distribución es uniforme, lo que implica que no hay una relación obvia entre esta variable y el objetivo (FraudFound_P). Se propone convertirla en dummies.</p>
</section>
<section id="detección-de-fraude-por-edad-del-titular-de-la-póliza" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-fraude-por-edad-del-titular-de-la-póliza"><em>05. Detección de Fraude por Edad del Titular de la Póliza</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separar datos de fraude y no fraude</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>df_fraud <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FraudFound_P <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>df_non_fraud <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FraudFound_P <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo por edad del titular de la póliza</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>df_counts_ageofpolicyholder <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(AgeOfPolicyHolder, <span class="at">name =</span> <span class="st">"Total"</span>)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>df_counts_fraud <span class="ot">&lt;-</span> df_fraud <span class="sc">%&gt;%</span> </span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(AgeOfPolicyHolder, <span class="at">name =</span> <span class="st">"Fraud"</span>)</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular porcentajes de fraude por edad</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>df_percentages_fraud <span class="ot">&lt;-</span> df_counts_ageofpolicyholder <span class="sc">%&gt;%</span> </span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_counts_fraud, <span class="at">by =</span> <span class="st">"AgeOfPolicyHolder"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fraud =</span> <span class="fu">replace_na</span>(Fraud, <span class="dv">0</span>),</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">Percentage =</span> <span class="fu">round</span>((Fraud <span class="sc">/</span> Total) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df_percentages_fraud)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  AgeOfPolicyHolder Total Fraud Percentage
1          18 to 20    15     2      13.33
2          21 to 25   108    16      14.81
3          26 to 30   613    33       5.38
4          31 to 35  5593   360       6.44
5          36 to 40  4043   237       5.86
6          41 to 50  2828   144       5.09
7          51 to 65  1392    70       5.03
8           over 65   508    30       5.91</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de barras con ggplot2</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_percentages_fraud, <span class="fu">aes</span>(<span class="at">x =</span> AgeOfPolicyHolder, <span class="at">y =</span> Percentage)) <span class="sc">+</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">6</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dotdash"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Línea de referencia</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Detección de Fraude por Edad del Titular de la Póliza"</span>,</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Edad del Titular de la Póliza"</span>,</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Porcentaje"</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">2</span>)) <span class="sc">+</span> <span class="co"># Configuración de rango y ticks</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">18</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/age-of-policyholder-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra que los titulares de pólizas jóvenes, especialmente entre 18 y 25 años, tienen una mayor incidencia de fraude, mientras que las personas mayores de 40 años presentan tasas significativamente menores.</p>
<p>Esto podría deberse a factores como inexperiencia financiera o mayor inclinación al riesgo en los más jóvenes, frente a estabilidad económica o experiencia en los mayores. Las aseguradoras podrían enfocar medidas preventivas específicas, como controles adicionales o campañas educativas, para reducir el fraude en los segmentos más propensos.</p>
</section>
<section id="detección-de-fraude-por-precio-del-vehículo" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-fraude-por-precio-del-vehículo"><em>06. Detección de Fraude por Precio del Vehículo</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular conteos de VehiclePrice en el dataset completo y en fraudes</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>df_counts_vp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(VehiclePrice, <span class="at">name =</span> <span class="st">"Total"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(VehiclePrice))</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>df_counts_fraud3 <span class="ot">&lt;-</span> df_fraud <span class="sc">%&gt;%</span> </span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(VehiclePrice, <span class="at">name =</span> <span class="st">"Fraud"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(VehiclePrice))</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinar conteos y calcular porcentajes</span></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>df_percentages_fraud3 <span class="ot">&lt;-</span> df_counts_vp <span class="sc">%&gt;%</span> </span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_counts_fraud3, <span class="at">by =</span> <span class="st">"VehiclePrice"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fraud =</span> <span class="fu">replace_na</span>(Fraud, <span class="dv">0</span>),</span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Fraud %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>((Fraud <span class="sc">/</span> Total) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="st">`</span><span class="at">Fraud %</span><span class="st">`</span>)</span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df_percentages_fraud3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     VehiclePrice Total Fraud Fraud %
1  60000 to 69000    87     4    4.60
2  30000 to 39000  3532   175    4.95
3  20000 to 29000  8079   421    5.21
4  40000 to 59000   461    31    6.72
5 more than 69000  1846   158    8.56
6 less than 20000  1095   103    9.41</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de barras horizontal con ggplot2</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_percentages_fraud3, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Fraud %</span><span class="st">`</span>, <span class="at">y =</span> <span class="fu">reorder</span>(VehiclePrice, <span class="fu">desc</span>(<span class="fu">as.numeric</span>(<span class="fu">factor</span>(VehiclePrice, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"More than 69000"</span>, <span class="st">"60000 to 69000"</span>, <span class="st">"40000 to 59000"</span>, <span class="st">"30000 to 39000"</span>, <span class="st">"20000 to 29000"</span>, <span class="st">"less than 20000"</span>))))))) <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"#9FF781"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">6</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">linetype =</span> <span class="st">"dotdash"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Línea de referencia</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Detección de Fraude por Precio del Vehículo"</span>,</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Porcentaje"</span>,</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Precio del Vehículo"</span></span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">16</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">16</span>, <span class="dv">2</span>)) <span class="sc">+</span> <span class="co"># Configuración de rango y ticks</span></span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb79-13"><a href="#cb79-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">18</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb79-14"><a href="#cb79-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb79-15"><a href="#cb79-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb79-16"><a href="#cb79-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/vehicle-price-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos observar como los porcentajes más altos de fraude se encuentran en las categorías de vehículos “menos de 20,000” y “más de 69,000”. Esto indica que los vehículos más baratos y los más caros son los más propensos a estar involucrados en casos de fraude.</p>
</section>
<section id="detección-de-fraude-por-marca-del-vehículo" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-fraude-por-marca-del-vehículo"><em>07. Detección de Fraude por Marca del Vehículo</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupación de datos y cálculo del porcentaje de fraude por marca</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>fraud_analysis <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Make) <span class="sc">%&gt;%</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Cases =</span> <span class="fu">n</span>(),</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fraud_Cases =</span> <span class="fu">sum</span>(FraudFound_P <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fraud_Percent =</span> <span class="fu">round</span>((Fraud_Cases <span class="sc">/</span> Total_Cases) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Fraud_Percent))  <span class="co"># Ordenar por mayor porcentaje de fraude</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar el análisis</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fraud_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 4
   Make      Total_Cases Fraud_Cases Fraud_Percent
   &lt;chr&gt;           &lt;int&gt;       &lt;int&gt;         &lt;dbl&gt;
 1 Mecedes             4           1         25   
 2 Accura            472          59         12.5 
 3 Saturn             58           6         10.3 
 4 Saab              108          11         10.2 
 5 Ford              450          33          7.33
 6 Mercury            83           6          7.23
 7 BMW                15           1          6.67
 8 Honda            2482         148          5.96
 9 Toyota           3121         186          5.96
10 Chevrolet        1681          94          5.59
11 Pontiac          3837         213          5.55
12 Mazda            2354         123          5.23
13 Nisson             30           1          3.33
14 VW                283           8          2.83
15 Dodge             108           2          1.85
16 Ferrari             2           0          0   
17 Jaguar              6           0          0   
18 Lexus               1           0          0   
19 Porche              5           0          0   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización: Barra horizontal de porcentaje de fraude por marca</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fraud_analysis, <span class="fu">aes</span>(<span class="at">x =</span> Fraud_Percent, <span class="at">y =</span> <span class="fu">reorder</span>(Make, Fraud_Percent))) <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightcoral"</span>) <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Porcentaje de Fraude por Marca de Coche"</span>,</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Porcentaje de Fraude"</span>,</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Marca del Coche"</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">6</span>, <span class="at">linetype =</span> <span class="st">"dotdash"</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea de referencia al 6%</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/vehicle-make-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mercedes destaca significativamente como la marca con el porcentaje más alto de casos de fraude, superando el 20%.</p>
<p>Por otro lado, Accura, Saturn y Saab también presentan porcentajes elevados de fraude, aunque menores que Mercedes. Con porcentajes cercanos al promedio, se encuentran marcas como Ford, Mercury, BMW, Toyota y Honda. Finalmente, podemos concluir que las marcas Lexus, Jaguar y Ferrari son las que menor porcentaje de fraude presentan.</p>
</section>
<section id="detección-de-fraude-por-edad-del-vehículo" class="level4">
<h4 class="anchored" data-anchor-id="detección-de-fraude-por-edad-del-vehículo"><em>08. Detección de Fraude por Edad del Vehículo</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupación de datos y cálculo del porcentaje de fraude por Age of Vehicle</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>fraud_analysis_vehicle_age <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(AgeOfVehicle) <span class="sc">%&gt;%</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Cases =</span> <span class="fu">n</span>(),</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fraud_Cases =</span> <span class="fu">sum</span>(FraudFound_P <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fraud_Percent =</span> <span class="fu">round</span>((Fraud_Cases <span class="sc">/</span> Total_Cases) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Fraud_Percent))  <span class="co"># Ordenar por mayor porcentaje de fraude</span></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar el análisis</span></span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fraud_analysis_vehicle_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  AgeOfVehicle Total_Cases Fraud_Cases Fraud_Percent
  &lt;chr&gt;              &lt;int&gt;       &lt;int&gt;         &lt;dbl&gt;
1 4 years              229          21          9.17
2 3 years              151          13          8.61
3 5 years             1357          95          7   
4 6 years             3448         228          6.61
5 7 years             5807         325          5.6 
6 more than 7         3980         206          5.18
7 2 years               73           3          4.11
8 new                   55           1          1.82</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización: Barra horizontal del porcentaje de fraude por Age of Vehicle</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fraud_analysis_vehicle_age, <span class="fu">aes</span>(<span class="at">x =</span> Fraud_Percent, <span class="at">y =</span> <span class="fu">reorder</span>(AgeOfVehicle, Fraud_Percent))) <span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Detección de fraude en función de la edad del vehículo"</span>,</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Porcentaje de Fraude"</span>,</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Edad del Vehículo"</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">6</span>, <span class="at">linetype =</span> <span class="st">"dotdash"</span>, <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea de referencia al 6%</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/vehicle-age-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los vehículos con una antigüedad de 3 a 5 años presentan los porcentajes de fraude más altos, superando el promedio global (línea discontinua).</p>
</section>
</section>
</section>
<section id="preprocesamiento-y-feature-engineering" class="level1">
<h1><em>2) Preprocesamiento y Feature Engineering</em></h1>
<p>Primero creamos la receta para poder añadir todos los pasos y luego aplicarla al conjunto de entrenamiento.</p>
<ul>
<li><strong>Paso 1: Conversión de Variables Binarias</strong></li>
</ul>
<p>Se convierten las variables categóricas AccidentArea, Sex, Fault, PoliceReportFiled, WitnessPresent, AgentType en variables binarias para facilitar el análisis y modelado.</p>
<ul>
<li><strong>Paso 2: Label Encoding para Variables Ordinales y Nominales</strong></li>
</ul>
<p>Se codifican variables como VehiclePrice, DriverRating, AgeOfVehicle y BasePolicy utilizando valores enteros basados en el orden lógico o categorías.</p>
<ul>
<li><strong>Paso 3: One-Hot Encoding</strong></li>
</ul>
<p>Se aplican transformaciones de One-Hot Encoding a las variables categóricas restantes como RepNumber, Year o Deductible.</p>
<ul>
<li><strong>Paso 4: Imputación de Valores Faltantes</strong></li>
</ul>
<p>Lo que hacemos aqui es realizar la <strong>imputación de valores faltantes</strong> para completar el dataset y evitar problemas en el entrenamiento del modelo. Para las variables numéricas, utiliza la <strong>mediana</strong> porque es robusta frente a valores atípicos, mientras que para las variables categóricas emplea la <strong>moda</strong> (el valor más frecuente).</p>
<ul>
<li><strong>Paso 5: Remover cualquier columna con varianza cero</strong></li>
</ul>
<p>El código elimina columnas con varianza cero, ya que no aportan información útil al modelo al tener todos los valores iguales, optimizando así la relevancia y eficiencia del dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>receta <span class="ot">&lt;-</span> <span class="fu">recipe</span>(FraudFound_P <span class="sc">~</span> ., <span class="at">data =</span> data_smote) <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Paso 1: Convertir variables AccidentArea, Sex, Fault, PoliceReportFiled, WitnessPresent, AgentType en binarias</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">AccidentArea =</span> <span class="fu">ifelse</span>(AccidentArea <span class="sc">==</span> <span class="st">"Urban"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sex =</span> <span class="fu">ifelse</span>(Sex <span class="sc">==</span> <span class="st">"Male"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fault =</span> <span class="fu">ifelse</span>(Fault <span class="sc">==</span> <span class="st">"Policy Holder"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">PoliceReportFiled =</span> <span class="fu">ifelse</span>(PoliceReportFiled <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">WitnessPresent =</span> <span class="fu">ifelse</span>(WitnessPresent <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">AgentType =</span> <span class="fu">ifelse</span>(AgentType <span class="sc">==</span> <span class="st">"Internal"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Paso 2: Convertir variables ordinales con label encoding</span></span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">VehiclePrice =</span> <span class="fu">as.integer</span>(<span class="fu">factor</span>(VehiclePrice, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Less than 20,000"</span>, <span class="st">"20,000 to 30,000"</span>, <span class="st">"30,000 to 40,000"</span>, <span class="st">"40,000 to 50,000"</span>, <span class="st">"More than 50,000"</span></span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>    ))),</span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">AgeOfVehicle =</span> <span class="fu">as.integer</span>(<span class="fu">factor</span>(AgeOfVehicle, <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt; 1 year"</span>, <span class="st">"1 year"</span>, <span class="st">"2 years"</span>, <span class="st">"3 years"</span>, <span class="st">"4 years"</span>, <span class="st">"5 years"</span>, <span class="st">"6 years"</span>, <span class="st">"7 years"</span>, <span class="st">"&gt; 7 years"</span></span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>    ))),</span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">BasePolicy =</span> <span class="fu">as.integer</span>(<span class="fu">factor</span>(BasePolicy, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Liability"</span>, <span class="st">"Collision"</span>, <span class="st">"Comprehensive"</span>)))</span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Paso 3: One-hot encoding para todas las variables categóricas restantes</span></span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>(), <span class="at">one_hot =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Paso 4: Imputación de valores faltantes</span></span>
<span id="cb86-28"><a href="#cb86-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_median</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span>  <span class="co"># Para variables numéricas</span></span>
<span id="cb86-29"><a href="#cb86-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_mode</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span>   <span class="co"># Para variables categóricas</span></span>
<span id="cb86-30"><a href="#cb86-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-31"><a href="#cb86-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Paso 5: Remover cualquier columna con varianza cero</span></span>
<span id="cb86-32"><a href="#cb86-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dividir-el-dataset-en-conjunto-de-entrenamiento-y-prueba" class="level3">
<h3 class="anchored" data-anchor-id="dividir-el-dataset-en-conjunto-de-entrenamiento-y-prueba">Dividir el Dataset en Conjunto de Entrenamiento y Prueba</h3>
<p>Dividimos el Dataset en un conjunto de Entrenamiento (70% del conjunto) y Prueba (30% del conjunto).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Para reproducibilidad</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data_smote, <span class="at">prop =</span> <span class="fl">0.7</span>, <span class="at">strata =</span> FraudFound_P)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar distribuciones</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Distribución en el conjunto de entrenamiento:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Distribución en el conjunto de entrenamiento:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(train_data<span class="sc">$</span>FraudFound_P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
5264 5305 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Distribución en el conjunto de prueba:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Distribución en el conjunto de prueba:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(test_data<span class="sc">$</span>FraudFound_P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
2257 2274 </code></pre>
</div>
</div>
<p>Preparar y aplicar la receta al conjunto de entrenamiento</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>preprocessed_train_data <span class="ot">&lt;-</span> <span class="fu">prep</span>(receta, <span class="at">training =</span> train_data) <span class="sc">%&gt;%</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bake</span>(<span class="at">new_data =</span> <span class="cn">NULL</span>)  <span class="co"># Transformar train_data usando la receta</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="creación-de-los-algoritmos-ridge-lasso-y-elastic-net-y-de-los-workflows-necesarios" class="level1">
<h1><em>3) Creación de los algoritmos (Ridge, Lasso y Elastic-Net) y de los workflows necesarios</em></h1>
<p>Se definen tres modelos de regresión penalizada:</p>
<ul>
<li><p>Ridge Regression: Penalización L2.</p></li>
<li><p>Lasso Regression: Penalización L1.</p></li>
<li><p>Elastic Net: Combinación de penalizaciones L1 y L2.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo Ridge</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>(</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">penalty =</span> <span class="fu">tune</span>(),  <span class="co"># Hiperparámetro a tunear</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mixture =</span> <span class="dv">0</span>        <span class="co"># Ridge (mixture = 0)</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo Lasso</span></span>
<span id="cb97-10"><a href="#cb97-10" aria-hidden="true" tabindex="-1"></a>lasso_model <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>(</span>
<span id="cb97-11"><a href="#cb97-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb97-12"><a href="#cb97-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">penalty =</span> <span class="fu">tune</span>(),  <span class="co"># Hiperparámetro a tunear</span></span>
<span id="cb97-13"><a href="#cb97-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mixture =</span> <span class="dv">1</span>        <span class="co"># Lasso (mixture = 1)</span></span>
<span id="cb97-14"><a href="#cb97-14" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb97-15"><a href="#cb97-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span>
<span id="cb97-16"><a href="#cb97-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-17"><a href="#cb97-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo Elastic Net</span></span>
<span id="cb97-18"><a href="#cb97-18" aria-hidden="true" tabindex="-1"></a>elastic_net_model <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>(</span>
<span id="cb97-19"><a href="#cb97-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb97-20"><a href="#cb97-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">penalty =</span> <span class="fu">tune</span>(),  <span class="co"># Hiperparámetro a tunear</span></span>
<span id="cb97-21"><a href="#cb97-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">mixture =</span> <span class="fu">tune</span>()   <span class="co"># Elastic Net (mixture entre 0 y 1)</span></span>
<span id="cb97-22"><a href="#cb97-22" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb97-23"><a href="#cb97-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Creamos un workflow para cada modelo, utilizando la receta y los conjuntos de entrenamiento</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>ridge_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(receta) <span class="sc">%&gt;%</span>  <span class="co"># Usar la receta creada anteriormente</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(ridge_model)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>lasso_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(receta) <span class="sc">%&gt;%</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lasso_model)</span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>elastic_net_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(receta) <span class="sc">%&gt;%</span></span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(elastic_net_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Posteriormente se crean los grids para la búsqueda de hiperparámetros, para Ridge y Lasso se sintoniza únicamente el parámetro de penalización y para Elastic Net se sintonizan tanto el parámetro de penalización como el de mezcla (mixture).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid de valores para los hiperparámetros</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid para Ridge (solo `penalty`)</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>ridge_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">penalty</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">0</span>)),  <span class="co"># Valores de 10^-4 a 10^0</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">10</span>                <span class="co"># 10 niveles</span></span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid para Lasso (solo `penalty`)</span></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>lasso_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">penalty</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">0</span>)),  <span class="co"># Valores de 10^-4 a 10^0</span></span>
<span id="cb99-12"><a href="#cb99-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">10</span>                <span class="co"># 10 niveles</span></span>
<span id="cb99-13"><a href="#cb99-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb99-14"><a href="#cb99-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-15"><a href="#cb99-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid para Elastic Net (incluye `penalty` y `mixture`)</span></span>
<span id="cb99-16"><a href="#cb99-16" aria-hidden="true" tabindex="-1"></a>elastic_net_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb99-17"><a href="#cb99-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">penalty</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">0</span>)),  <span class="co"># Valores de 10^-4 a 10^0</span></span>
<span id="cb99-18"><a href="#cb99-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mixture</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),   <span class="co"># Valores entre 0 (Ridge) y 1 (Lasso)</span></span>
<span id="cb99-19"><a href="#cb99-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">10</span>                <span class="co"># 10 niveles por dimensión</span></span>
<span id="cb99-20"><a href="#cb99-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="validación-cruzada-y-tuneado-de-modelos" class="level1">
<h1><em>4) Validación Cruzada y Tuneado de Modelos</em></h1>
<p>Procedemos a ajustar los hiperparámetros mediante validación cruzada para evaluar el desempeño del modelo en diferentes subconjuntos de los datos de entrenamiento. Esto ayuda a prevenir el sobreajuste y asegura que los modelos sean generalizables.</p>
<p><strong>Configuración de la Validación Cruzada:</strong> Se divide el conjunto de entrenamiento en 5 particiones estratificadas, preservando la proporción de clases de la variable objetivo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuración de la validación cruzada</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># Para reproducibilidad</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>cv_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> FraudFound_P)</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificación de los folds creados</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Validación cruzada (5 folds):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Validación cruzada (5 folds):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cv_folds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#  5-fold cross-validation using stratification 
# A tibble: 5 × 2
  splits              id   
  &lt;list&gt;              &lt;chr&gt;
1 &lt;split [8455/2114]&gt; Fold1
2 &lt;split [8455/2114]&gt; Fold2
3 &lt;split [8455/2114]&gt; Fold3
4 &lt;split [8455/2114]&gt; Fold4
5 &lt;split [8456/2113]&gt; Fold5</code></pre>
</div>
</div>
<p><strong>Métricas de Evaluación.</strong> Se seleccionan métricas para evaluar el desempeño de los modelos:</p>
<ul>
<li><p><strong>ROC AUC</strong>: Área bajo la curva ROC, mide la capacidad del modelo para separar las clases.</p></li>
<li><p><strong>Accuracy</strong>: Porcentaje de predicciones correctas.</p></li>
<li><p><strong>F-measure</strong>: Media armónica entre precisión y recall.</p></li>
<li><p><strong>Precision</strong>: Proporción de predicciones positivas correctas.</p></li>
<li><p><strong>Recall</strong>: Proporción de verdaderos positivos identificados correctamente.</p></li>
</ul>
<p><strong>Sintonización de Hiperparámetros.</strong> En esta etapa se realizan búsquedas en los grids de hiperparámetros para cada modelo utilizando validación cruzada. Esto permite seleccionar los mejores valores de penalización y mezcla.</p>
<ol type="1">
<li><p><strong>Tuneado para Ridge:</strong> el modelo Ridge busca optimizar el parámetro de penalización L2 a través de una grid especificada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Ridge Model</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>ridge_tuned_results <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>  ridge_workflow,</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> cv_folds,</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> ridge_grid,</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas)  <span class="co"># Métricas de evaluación</span></span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Tuneado para Lasso:</strong> el modelo Lasso optimiza el parámetro de penalización L1 usando la misma técnica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lasso Model</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>lasso_tuned_results <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>  lasso_workflow,</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> cv_folds,</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> lasso_grid,</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas)</span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: While computing binary `precision()`, no predicted events were detected (i.e.
               `true_positive + false_positive = 0`).
               Precision is undefined in this case, and `NA` will be returned.
               Note that 1053 true event(s) actually occurred for the problematic event level,
               0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ B | warning: While computing binary `precision()`, no predicted events were detected (i.e.
               `true_positive + false_positive = 0`).
               Precision is undefined in this case, and `NA` will be returned.
               Note that 1052 true event(s) actually occurred for the problematic event level,
               0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x4
There were issues with some computations   A: x4   B: x1</code></pre>
</div>
</div></li>
<li><p><strong>Tuneado para Elastic-Net:</strong>&nbsp;el modelo Elastic-Net ajusta tanto la penalización como el parámetro de mezcla (L1 y L2 combinados).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Elastic Net Model</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>elastic_net_tuned_results <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  elastic_net_workflow,</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> cv_folds,</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> elastic_net_grid,</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas)</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: While computing binary `precision()`, no predicted events were detected (i.e.
               `true_positive + false_positive = 0`).
               Precision is undefined in this case, and `NA` will be returned.
               Note that 1053 true event(s) actually occurred for the problematic event level,
               0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ B | warning: While computing binary `precision()`, no predicted events were detected (i.e.
               `true_positive + false_positive = 0`).
               Precision is undefined in this case, and `NA` will be returned.
               Note that 1052 true event(s) actually occurred for the problematic event level,
               0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x4
There were issues with some computations   A: x4   B: x1
There were issues with some computations   A: x4   B: x1</code></pre>
</div>
</div></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los mejores resultados de cada modelo</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Mejores resultados para Ridge:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mejores resultados para Ridge:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(ridge_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
   penalty .metric .estimator  mean     n std_err .config              
     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
1 0.0001   roc_auc binary     0.821     5 0.00173 Preprocessor1_Model01
2 0.000278 roc_auc binary     0.821     5 0.00173 Preprocessor1_Model02
3 0.000774 roc_auc binary     0.821     5 0.00173 Preprocessor1_Model03
4 0.00215  roc_auc binary     0.821     5 0.00173 Preprocessor1_Model04
5 0.00599  roc_auc binary     0.821     5 0.00173 Preprocessor1_Model05</code></pre>
</div>
</div>
<ul>
<li><p>El mejor valor de la métrica <code>roc_auc</code> es 0.8209533.</p></li>
<li><p>Los resultados son consistentes en todas las configuraciones del hiperparámetro <code>penalty</code>, lo que sugiere que el modelo no es particularmente sensible a este ajuste.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Mejores resultados para Lasso:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mejores resultados para Lasso:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(lasso_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
   penalty .metric .estimator  mean     n std_err .config              
     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
1 0.00215  roc_auc binary     0.821     5 0.00168 Preprocessor1_Model04
2 0.000774 roc_auc binary     0.821     5 0.00182 Preprocessor1_Model03
3 0.000278 roc_auc binary     0.821     5 0.00184 Preprocessor1_Model02
4 0.0001   roc_auc binary     0.821     5 0.00186 Preprocessor1_Model01
5 0.00599  roc_auc binary     0.820     5 0.00170 Preprocessor1_Model05</code></pre>
</div>
</div>
<ul>
<li><p>El mejor valor de <code>roc_auc</code> es ligeramente superior a Ridge, alcanzando 0.8210513.</p></li>
<li><p>Existe una pequeña variabilidad en los resultados para diferentes valores de <code>penalty</code>, pero sigue siendo marginal.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Mejores resultados para Elastic Net:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mejores resultados para Elastic Net:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(elastic_net_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  penalty mixture .metric .estimator  mean     n std_err .config               
    &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                 
1 0.00599   0.333 roc_auc binary     0.821     5 0.00160 Preprocessor1_Model035
2 0.00599   0.111 roc_auc binary     0.821     5 0.00167 Preprocessor1_Model015
3 0.00599   0.222 roc_auc binary     0.821     5 0.00163 Preprocessor1_Model025
4 0.00599   0.444 roc_auc binary     0.821     5 0.00159 Preprocessor1_Model045
5 0.00215   0.333 roc_auc binary     0.821     5 0.00177 Preprocessor1_Model034</code></pre>
</div>
</div>
<ul>
<li><p>Elastic Net ofrece una ligera ventaja, alcanzando un <code>roc_auc</code> máximo de 0.8213736.</p></li>
<li><p>Dado que Elastic Net combina características de Ridge y Lasso, parece aprovechar mejor los patrones de los datos, siendo el modelo con mejor desempeño general.</p></li>
</ul>
<p><strong>Conclusión</strong>: Aunque las diferencias en el rendimiento son mínimas, Elastic Net logra el mejor <code>roc_auc</code>, lo que lo hace una elección ligeramente preferible en este caso.</p>
</section>
<section id="assessment-con-validación-cruzada" class="level1">
<h1><em>5) Assessment con Validación Cruzada</em></h1>
<p>En esta etapa se seleccionan los mejores hiperparámetros para cada modelo basado en la métrica de&nbsp;<strong>ROC AUC</strong>. Posteriormente, se realiza una validación cruzada con los modelos ajustados para evaluar su desempeño.</p>
<p><strong>Selección de los Mejores Hiperparámetros</strong></p>
<p>Los mejores hiperparámetros para cada modelo se eligen según la métrica <strong>ROC AUC</strong>, que evalúa la capacidad del modelo para distinguir entre clases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar los mejores hiperparámetros para cada modelo</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>best_params_ridge <span class="ot">&lt;-</span> <span class="fu">select_best</span>(ridge_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>best_params_lasso <span class="ot">&lt;-</span> <span class="fu">select_best</span>(lasso_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>best_params_elastic_net <span class="ot">&lt;-</span> <span class="fu">select_best</span>(elastic_net_tuned_results, <span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Validación Cruzada con los Mejores Modelos</strong></p>
<p>Se realiza una validación cruzada con los mejores hiperparámetros seleccionados para evaluar métricas como precisión, recall y F1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nueva validación cruzada con otra partición</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)  <span class="co"># Cambiar la semilla</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>new_cv_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> FraudFound_P)</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Función para evaluar modelos en nueva validación cruzada</span></span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>evaluar_modelo_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(workflow, folds, metricas) {</span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a>  resultado_cv <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(</span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a>    workflow,</span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> folds,</span>
<span id="cb133-10"><a href="#cb133-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> metricas</span>
<span id="cb133-11"><a href="#cb133-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb133-12"><a href="#cb133-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(resultado_cv)</span>
<span id="cb133-13"><a href="#cb133-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Resultados del Assessment</strong></p>
<ul>
<li>Finalmente, se recopilan y muestran las métricas de desempeño para cada modelo.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluación de cada modelo</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Evaluación del modelo Ridge con nueva validación cruzada:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Evaluación del modelo Ridge con nueva validación cruzada:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>ridge_new_cv_metrics <span class="ot">&lt;-</span> <span class="fu">evaluar_modelo_cv</span>(<span class="fu">finalize_workflow</span>(ridge_workflow, best_params_ridge),</span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>                                          new_cv_folds,</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas))</span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ridge_new_cv_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  .metric   .estimator  mean     n std_err .config             
  &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 accuracy  binary     0.763     5 0.00221 Preprocessor1_Model1
2 f_meas    binary     0.716     5 0.00316 Preprocessor1_Model1
3 precision binary     0.889     5 0.00535 Preprocessor1_Model1
4 recall    binary     0.600     5 0.00497 Preprocessor1_Model1
5 roc_auc   binary     0.819     5 0.00257 Preprocessor1_Model1</code></pre>
</div>
</div>
<ul>
<li><p><strong>Accuracy</strong>: El modelo tiene una accuracy del <strong>76.32%</strong>, lo que indica que el modelo clasifica correctamente alrededor del 76% de las observaciones en promedio.</p></li>
<li><p><strong>F-Measure (f_meas)</strong>: El valor promedio del F-measure es <strong>71.6%</strong>, lo que refleja un equilibrio entre precisión y sensibilidad.</p></li>
<li><p><strong>Precisión</strong>: La precisión promedio es <strong>88.9%</strong>, lo que indica que, cuando el modelo predice una clase positiva, lo hace correctamente casi el 89% de las veces.</p></li>
<li><p><strong>Recall</strong>: El valor del recall promedio es <strong>59.95%</strong>, lo que significa que el modelo identifica correctamente menos del 60% de las instancias positivas reales.</p></li>
<li><p><strong>Área bajo la curva ROC (roc_auc)</strong>: El valor promedio del AUC es <strong>81.97%</strong>, lo que indica que el modelo tiene una buena capacidad para distinguir entre las clases positivas y negativas.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Evaluación del modelo Lasso con nueva validación cruzada:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Evaluación del modelo Lasso con nueva validación cruzada:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>lasso_new_cv_metrics <span class="ot">&lt;-</span> <span class="fu">evaluar_modelo_cv</span>(<span class="fu">finalize_workflow</span>(lasso_workflow, best_params_lasso),</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>                                          new_cv_folds,</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas))</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(lasso_new_cv_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  .metric   .estimator  mean     n std_err .config             
  &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 accuracy  binary     0.767     5 0.00264 Preprocessor1_Model1
2 f_meas    binary     0.717     5 0.00404 Preprocessor1_Model1
3 precision binary     0.904     5 0.00422 Preprocessor1_Model1
4 recall    binary     0.594     5 0.00570 Preprocessor1_Model1
5 roc_auc   binary     0.820     5 0.00203 Preprocessor1_Model1</code></pre>
</div>
</div>
<ul>
<li><p><strong>Accuracy</strong>: El modelo tiene una accuracy promedio de <strong>76.66%</strong>, lo que significa que clasifica correctamente aproximadamente el 76.7% de las observaciones en promedio.</p></li>
<li><p><strong>F-Measure (f_meas)</strong>: El F-measure promedio es <strong>71.72%</strong>, lo que refleja un balance entre precisión y sensibilidad.</p></li>
<li><p><strong>Precisión</strong>: La precisión promedio es <strong>90.42%</strong>, un valor alto, lo que indica que el modelo predice la clase positiva con mucha confianza (baja tasa de falsos positivos).</p></li>
<li><p><strong>Recall</strong>: EL valor del Recall promedio es <strong>59.44%</strong>, lo que indica que el modelo identifica correctamente menos del 60% de las instancias positivas reales.</p></li>
<li><p><strong>Área bajo la curva ROC (roc_auc)</strong>: El valor promedio del AUC es <strong>81.98%</strong>, lo que demuestra una buena capacidad del modelo para distinguir entre las clases positivas y negativas.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Evaluación del modelo Elastic Net con nueva validación cruzada:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Evaluación del modelo Elastic Net con nueva validación cruzada:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>elastic_net_new_cv_metrics <span class="ot">&lt;-</span> <span class="fu">evaluar_modelo_cv</span>(<span class="fu">finalize_workflow</span>(elastic_net_workflow, best_params_elastic_net),</span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>                                                new_cv_folds,</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a>                                                <span class="fu">metric_set</span>(roc_auc, accuracy, recall, precision, f_meas))</span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(elastic_net_new_cv_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  .metric   .estimator  mean     n std_err .config             
  &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 accuracy  binary     0.767     5 0.00232 Preprocessor1_Model1
2 f_meas    binary     0.718     5 0.00369 Preprocessor1_Model1
3 precision binary     0.905     5 0.00432 Preprocessor1_Model1
4 recall    binary     0.595     5 0.00558 Preprocessor1_Model1
5 roc_auc   binary     0.820     5 0.00230 Preprocessor1_Model1</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>Accuracy</strong>: El modelo Elastic Net tiene una accuracy promedio de <strong>76.71%</strong>, lo que muestra un buen desempeño en términos de clasificaciones correctas generales.</p></li>
<li><p><strong>F-Measure (f_meas)</strong>: El F-measure promedio es <strong>71.78%</strong>, lo que indica un balance razonable entre la precisión y la sensibilidad del modelo.</p></li>
<li><p><strong>Precisión</strong> : La precisión promedio es <strong>90.53%</strong>, lo que significa que el modelo realiza predicciones positivas con alta confiabilidad (baja tasa de falsos positivos).</p></li>
<li><p><strong>Recall</strong>: El Recall promedio es <strong>59.48%</strong>, lo que muestra que el modelo identifica correctamente menos del 60% de las instancias positivas reales.</p></li>
<li><p><strong>Área bajo la curva ROC (roc_auc)</strong>: El valor promedio del AUC es <strong>81.99%</strong>, lo que demuestra una buena capacidad de discriminación entre clases positivas y negativas.</p></li>
</ol>
</section>
<section id="selección-del-mejor-modelo-y-evaluación-final" class="level1">
<h1><em>6) Selección del mejor modelo y evaluación final</em></h1>
<p>Realizamos la <strong>selección del mejor modelo</strong> en función de la métrica <code>roc_auc</code> y se evalúa su desempeño final.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a>mejor_modelo <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ridge =</span> ridge_new_cv_metrics,</span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Lasso =</span> lasso_new_cv_metrics,</span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ElasticNet =</span> elastic_net_new_cv_metrics</span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb146-6"><a href="#cb146-6" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map_dfr</span>(<span class="sc">~</span>.x <span class="sc">%&gt;%</span> <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"roc_auc"</span>), <span class="at">.id =</span> <span class="st">"Modelo"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb146-7"><a href="#cb146-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span>
<span id="cb146-8"><a href="#cb146-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-9"><a href="#cb146-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">El mejor modelo es:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
El mejor modelo es:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mejor_modelo[<span class="dv">1</span>, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  Modelo     .metric .estimator  mean     n std_err .config             
  &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 ElasticNet roc_auc binary     0.820     5 0.00230 Preprocessor1_Model1</code></pre>
</div>
</div>
<p>El modelo de Elastic Net ha obtenido un valor de <strong>ROC AUC</strong> de <strong>0.8199</strong> en la validación cruzada, lo cual indica que tiene un rendimiento bastante bueno para la clasificación de las observaciones. Además, el error estándar asociado es <strong>0.0023</strong>, lo que sugiere que el valor de la métrica es relativamente estable y confiable a través de las diferentes divisiones del conjunto de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el mejor modelo en todo el conjunto de entrenamiento</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (mejor_modelo<span class="sc">$</span>Modelo[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"Ridge"</span>) {</span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a>  final_workflow <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(ridge_workflow, best_params_ridge)</span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (mejor_modelo<span class="sc">$</span>Modelo[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"Lasso"</span>) {</span>
<span id="cb150-5"><a href="#cb150-5" aria-hidden="true" tabindex="-1"></a>  final_workflow <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(lasso_workflow, best_params_lasso)</span>
<span id="cb150-6"><a href="#cb150-6" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb150-7"><a href="#cb150-7" aria-hidden="true" tabindex="-1"></a>  final_workflow <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(elastic_net_workflow, best_params_elastic_net)</span>
<span id="cb150-8"><a href="#cb150-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo final en el conjunto completo de entrenamiento</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a>final_fit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(final_workflow, <span class="at">split =</span> data_split)</span>
<span id="cb151-4"><a href="#cb151-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-5"><a href="#cb151-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Métricas finales en el conjunto de prueba</span></span>
<span id="cb151-6"><a href="#cb151-6" aria-hidden="true" tabindex="-1"></a>final_metrics <span class="ot">&lt;-</span> <span class="fu">collect_metrics</span>(final_fit)</span>
<span id="cb151-7"><a href="#cb151-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Métricas finales en el conjunto de prueba:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Métricas finales en el conjunto de prueba:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(final_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  .metric     .estimator .estimate .config             
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
1 accuracy    binary         0.761 Preprocessor1_Model1
2 roc_auc     binary         0.812 Preprocessor1_Model1
3 brier_class binary         0.164 Preprocessor1_Model1</code></pre>
</div>
</div>
<p><strong>Ajustamos el modelo final en el conjunto completo de entrenamiento</strong> y para <strong>evaluar su rendimiento</strong> en el conjunto de prueba.</p>
</section>
<section id="predicción-y-métricas-sobre-el-conjunto-de-prueba" class="level1">
<h1><em>7) Predicción y métricas sobre el conjunto de prueba</em></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar predicciones sobre el conjunto de prueba</span></span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">collect_predictions</span>(final_fit)</span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb155-4"><a href="#cb155-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar las primeras filas de las predicciones</span></span>
<span id="cb155-5"><a href="#cb155-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Predicciones en el conjunto de prueba:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Predicciones en el conjunto de prueba:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(test_predictions))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  .pred_class .pred_0 .pred_1 id                .row FraudFound_P .config       
  &lt;fct&gt;         &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;            &lt;int&gt; &lt;fct&gt;        &lt;chr&gt;         
1 1             0.340 0.660   train/test split     3 0            Preprocessor1…
2 0             0.995 0.00472 train/test split     4 0            Preprocessor1…
3 0             0.898 0.102   train/test split     7 0            Preprocessor1…
4 0             0.957 0.0434  train/test split     8 0            Preprocessor1…
5 1             0.381 0.619   train/test split    10 0            Preprocessor1…
6 1             0.150 0.850   train/test split    11 0            Preprocessor1…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular métricas de clasificación sobre el conjunto de prueba</span></span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a>test_metrics <span class="ot">&lt;-</span> test_predictions <span class="sc">%&gt;%</span></span>
<span id="cb159-3"><a href="#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> FraudFound_P, <span class="at">estimate =</span> .pred_class, .pred_1) <span class="sc">%&gt;%</span></span>
<span id="cb159-4"><a href="#cb159-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"accuracy"</span>, <span class="st">"precision"</span>, <span class="st">"recall"</span>, <span class="st">"f_meas"</span>, <span class="st">"roc_auc"</span>))</span>
<span id="cb159-5"><a href="#cb159-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-6"><a href="#cb159-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Métricas de clasificación para el conjunto de prueba:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Métricas de clasificación para el conjunto de prueba:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.761
2 roc_auc  binary         0.188</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>Accuracy</strong>: La accuracy es de <strong>0.7603</strong>. Esto significa que aproximadamente el 76% de las predicciones fueron correctas, es decir, el modelo acertó en clasificar correctamente las instancias de fraude y no fraude.</p></li>
<li><p><strong>Precision</strong>: La precisión es de <strong>0.9024</strong>. Este valor indica que de todas las observaciones que el modelo predijo como “fraude” (clase <code>1</code>), el 90.24% fueron realmente casos de fraude. La precisión muestra que el modelo tiene un buen rendimiento al evitar falsos positivos.</p></li>
<li><p><strong>Recall</strong>: El recall es de <strong>0.5817</strong>. Esto significa que de todas las instancias que realmente eran fraude, el modelo identificó correctamente el 58.17% de ellas. Un recall bajo podría ser indicativo de que el modelo no está detectando todos los casos de fraude.</p></li>
<li><p><strong>F1-Score</strong>: El F1-Score es de <strong>0.7074</strong>, lo cual es una combinación armónica entre la precisión y el recall. Es un valor equilibrado que refleja el rendimiento del modelo en cuanto a detectar fraude, dado el compromiso entre precisión y recall. Un F1-Score de 0.7074 indica que el modelo tiene un buen rendimiento global, pero con espacio para mejorar, especialmente en la detección de todos los fraudes (recall).</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear matriz de confusión</span></span>
<span id="cb163-2"><a href="#cb163-2" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> test_predictions <span class="sc">%&gt;%</span></span>
<span id="cb163-3"><a href="#cb163-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conf_mat</span>(<span class="at">truth =</span> FraudFound_P, <span class="at">estimate =</span> .pred_class)</span>
<span id="cb163-4"><a href="#cb163-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb163-5"><a href="#cb163-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Matriz de confusión:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Matriz de confusión:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction    0    1
         0 1315  142
         1  942 2132</code></pre>
</div>
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización de la matriz de confusión</span></span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(confusion_matrix, <span class="at">type =</span> <span class="st">"heatmap"</span>) <span class="sc">+</span></span>
<span id="cb167-3"><a href="#cb167-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb167-4"><a href="#cb167-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Matriz de Confusión"</span>,</span>
<span id="cb167-5"><a href="#cb167-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predicción"</span>,</span>
<span id="cb167-6"><a href="#cb167-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Real"</span></span>
<span id="cb167-7"><a href="#cb167-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb167-8"><a href="#cb167-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FraudeCocheQuarto16_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="conclusiones-de-la-matriz-de-confusión" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones-de-la-matriz-de-confusión">Conclusiones de la matriz de confusión:</h3>
<ol type="1">
<li><p><strong>True Positives (TP)</strong>: El modelo ha identificado correctamente <strong>2132 casos de fraude</strong> (Predicción 1 y Real 1). Esto indica que el modelo tiene una capacidad considerable para identificar correctamente los casos de fraude.</p></li>
<li><p><strong>True Negatives (TN)</strong>: El modelo ha identificado correctamente <strong>1313 casos de no fraude</strong> (Predicción 0 y Real 0), lo que significa que también es bastante eficaz al identificar las transacciones no fraudulentas.</p></li>
<li><p><strong>False Positives (FP)</strong>: El modelo ha cometido <strong>142 errores al clasificar casos no fraudulentos como fraudulentos</strong>. Esto genera lo que se conoce como un <strong>falso positivo</strong>, es decir, predicciones erróneas donde el modelo clasificó incorrectamente como fraude casos que en realidad no lo eran. Aunque este número no es muy alto, siempre es importante considerar los falsos positivos, ya que pueden generar costos adicionales o inconvenientes, dependiendo de la aplicación.</p></li>
<li><p><strong>False Negatives (FN)</strong>: El modelo ha dejado de identificar <strong>944 casos de fraude</strong> correctamente. Estos son los <strong>falsos negativos</strong>, que representan las transacciones fraudulentas que fueron clasificadas incorrectamente como no fraudulentas. Este es un aspecto crítico en la detección de fraude, ya que un falso negativo significa que un fraude pasó desapercibido, lo que puede tener consecuencias graves.</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>